### ISSUE TITLE
Moteur de template

### ISSUE THREAD

**Issue by theomi** [dil-classroom/projet-bailat_huart_mirabile_praz#33]
En tant qu’utilisateur, j’aimerai pouvoir utiliser un moteur de template (p.ex. Handlebars1) de manière à enrichir
mes pages HTML avec des éléments d’interfaces (header, footer, menu, etc.). En d’autres termes, j’aimerai que le
HTML correspondant à mes fichiers Markdown soit injecté dans des pages HTML plus complètes à l’aide d’un
template.

- [ ] Parsing des métadonnées des pages
- [ ] Mise en place du contexte (variables) du moteur de templating
- [ ] Intégration de Handlebars

**Estimations temporelles :**
- Optimiste : 3 heures
- Attendu : 4 heures
- Pessimiste : 6 heures

**Comment by PrazTobie** [comment]
Temps effectif: 5 heures
