### ISSUE TITLE
Continuous delivery

### ISSUE THREAD

**Issue by theomi** [dil-classroom/projet-bailat_huart_mirabile_praz#35]
En tant que développeur, j’aimerai que la création et la publication d’une nouvelle release soit automatisée à l’aide de GitHub actions. En d’autres termes, j’aimerai que le fichier jar ou le fichier zip de la release soit publié de manière automatique lorsqu’un tag correspondant à une version (p. ex. v0.0.2) est publié sur git.
**Estimations temporelles :**
- Optimiste : 1 heure
- Attendu : 2 heures
- Pessimiste : 3 heures

**Comment by HUART1848** [comment]
Temps effectué : **2h**
