### ISSUE TITLE
Génération du site statique à la volée

### ISSUE THREAD

**Issue by theomi** [dil-classroom/projet-bailat_huart_mirabile_praz#42]
En tant qu’utilisateur, j’aimerai que les commandes build et serve puissent régénérer le site statique à la volée, c’est-à-dire de manière automatique lorsque des changements sont effectués sur le système de fichier. Pour cela, ajoutez une option `--watch` aux commandes build et serve et assurez-vous que leur exécution ne se termine pas à la fin du premier build.
Les générateurs de site statique Jekyll1 et Hugo2 disposent tous deux d’une option `--watch`. La WatchService API3 de la librairie standard Java permet d’écouter les changements effectués sur le système de fichiers.

- [x] Détecter les changements sur les fichiers sources (optimiste : 1h, attendu : 2h, pessimiste : 3h)
- [x] Implémenter l'option `--watch` dans `build` et `serve` (optimiste : 1h, attendu : 1h, pessimiste : 2h)
- [x] Implémenter la compilation automatique (optimiste : 1h, attendu : 1h, pessimiste : 2h)

**Comment by PrazTobie** [comment]
Temps effectif: 5 heures
