### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by theomi** [dil-classroom/projet-bailat_huart_mirabile_praz#47]
Configurez LGTM, SonarQube ou un outil équivalent pour détecter des bugs et des vulnérabilités dans votre code.
Expliquez en quoi l’un de ces outils vous aura permis d’améliorer vos pratiques de développement.

- Optimiste : 2h
- Attendu : 4h
- Pessimiste : 6h

**Comment by HUART1848** [comment]
Temps effectif: 1H
